version: '3.1'

services:
#  mysql:
#    container_name: mysql
#    image: mysql:8.0.32
#    environment:
#      - MYSQL_DATABASE=managementsystem
#      - MYSQL_ROOT_PASSWORD=haiduong
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - '3306:3306'
#    expose:
#      - 3306
#    restart: unless-stopped

#
#  springboot:
#    container_name: springboot
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kafka

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped